name: site2tg-autonews
on:
  schedule:
    # каждые 2 часа (07–23 МСК = 04–20 UTC)
    - cron: "0 4-20/2 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install requests beautifulsoup4
      - name: Run multi-site poster
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_THREAD_ID: ${{ secrets.TELEGRAM_THREAD_ID }}            # если нужна тема для обоих
          TELEGRAM_COPY_TO_CHAT_ID: ${{ secrets.TELEGRAM_COPY_TO_CHAT_ID }} # если нужно копировать
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}                     # LLM-стилизация
        run: |
          python run_sites.py
